import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../../../../Ecell/ecell/src/app/components/Navbar";
import { Button } from "./components/ui/moving-border";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div className="relative w-full sm:w-16 bg-neutral-800 items-center justify-center">
          <Navbar />
        </div>
        {children}
      </body>
    </html>
  );
}
